name: Lightningstick
version: ${project.version}
main: me.burzakrual.lightningstick.Main
api-version: 1.16
authors: [ BurzaKrual ]
description: It's a lightning stick!
commands:
  lstick:
    usage: /<command>


permissions:
  lstick.get:
    description: You need this permission.
    default: op